Update 0295-codable-synthesis-for-enums-with-associated-values.md
apple/swift-evolution pull request #1381
Opened 2021-06-04 10:45 UTC by puretears

`case store` is excluded by the declaration of `CodingKeys`.

2021-06-22 21:00 UTC, tomerd commented
cc @drexin

2021-06-22 21:07 UTC, drexin requested changes

2021-06-22 21:07 UTC, drexin commented on proposals/0295-codable-synthesis-for-enums-with-associated-values.md
> +    "key": "MyKey"
Thanks for spotting this. Using `"schluessel"` here was intended, but the `enum StoreCodingKeys` above should instead be `LoadCodingKeys` and `_1` removed.

2021-07-19 19:10 UTC, drexin commented on proposals/0295-codable-synthesis-for-enums-with-associated-values.md
> +    "key": "MyKey"
@puretears ping

2021-08-17 20:17 UTC, DougGregor commented
@drexin can you look into fixing the typo in the proposal, whether by addressing your comments in the PR directly or opening a separate PR to do so?

2021-08-17 20:29 UTC, drexin commented
@DougGregor Will do.

2021-08-17 21:59 UTC, drexin commented
@DougGregor https://github.com/apple/swift-evolution/pull/1426

2021-08-18 11:46 UTC, DougGregor commented
This has been subsumed by #1426

2021-08-18 11:47 UTC, closed without merging